from typing import Any, Iterator, Protocol

class _PathModule(Protocol):
    def join(self, *paths: str) -> str: ...
    def abspath(self, path: str) -> str: ...
    def dirname(self, path: str) -> str: ...
    def basename(self, path: str) -> str: ...

path: _PathModule
sep: str
environ: dict[str, str]

def getcwd() -> str: ...
def listdir(path: str = ...) -> list[str]: ...
def makedirs(name: str, exist_ok: bool = ...) -> None: ...
def remove(path: str) -> None: ...
def rename(src: str, dst: str) -> None: ...
def rmdir(path: str) -> None: ...
def stat(path: str) -> Any: ...
def statvfs(path: str) -> tuple[int, ...]: ...
def uname() -> Any: ...
