from typing import Any, Protocol

class _PathModule(Protocol):
    def join(self, *paths: str) -> str: ...
    def abspath(self, path: str) -> str: ...
    def dirname(self, path: str) -> str: ...
    def basename(self, path: str) -> str: ...

path: _PathModule
sep: str

def getcwd() -> str: ...
def makedirs(name: str, exist_ok: bool = ...) -> None: ...
def remove(path: str) -> None: ...
def stat(path: str) -> Any: ...
