# Golden-vector + scenario tests for the regulation matrix.
#
# The golden CSVs under tests/golden/ are generated by
# prototypes/plot_regulation_surfaces.py and blessed by the operator. The
# device surface math must reproduce them within +/-1 (this catches
# MicroPython float divergence near hinge breakpoints when run on-device, and
# catches accidental config/param drift when run on host — a changed surface
# fails until the golden CSV is regenerated).

from pathlib import Path

import pytest

_GOLDEN_DIR = Path(__file__).resolve().parent / "golden"


def _surface_names():
    import config

    regs = config.DEVICE_CONFIG["regulation"]["regulators"]
    return [n for n in config._REG_NAMES if regs[n].get("driven") == "surface"]


class TestGoldenVectors:
    def test_golden_file_exists_for_each_surface(self):
        for name in _surface_names():
            path = _GOLDEN_DIR / "regulation_{}.csv".format(name)
            assert path.exists(), "missing golden vectors for {} (run the host tool)".format(name)

    @pytest.mark.parametrize("name", _surface_names())
    def test_device_math_matches_golden(self, name):
        import config
        from lib.regulation_surface import evaluate, freeze_surface

        params = freeze_surface(config.DEVICE_CONFIG["regulation"]["regulators"][name]["surface"])
        path = _GOLDEN_DIR / "regulation_{}.csv".format(name)
        with open(path) as fh:
            header = fh.readline().strip()
            assert header == "x,y,out"
            for line in fh:
                x_s, y_s, out_s = line.strip().split(",")
                x, y, expected = float(x_s), float(y_s), float(out_s)
                got = evaluate(params, x, y)
                assert abs(got - expected) <= 1.0, "{} at ({},{}): {} vs golden {}".format(name, x, y, got, expected)


# ---------------------------------------------------------------------------
# Scenario table: (temp, RH, CO2) → expected actuation direction per regulator.
# ---------------------------------------------------------------------------


class _Adapter:
    def __init__(self, name):
        self.name = name
        self.value = 0.0
        self.active = False

    def apply(self, intensity, now_s):
        self.value = intensity
        self.active = intensity > 0.0


class _Th:
    def __init__(self, t, h):
        self.last_temperature = t
        self.last_humidity = h


class _Co2:
    def __init__(self, ppm):
        self.last_ppm = ppm


class _Time:
    def __init__(self, minutes):
        self._s = minutes * 60

    def get_seconds_since_midnight(self):
        return self._s


def _run_scenario(temp, hum, co2, minutes=720, external_read=None):
    import copy

    import config
    from lib.regulation_engine import RegulationEngine

    reg = copy.deepcopy(config.DEVICE_CONFIG["regulation"])
    if external_read is not None:
        reg["external_sensor"]["enabled"] = True
    names = config._REG_NAMES
    adapters = [_Adapter(n) for n in names]
    engine = RegulationEngine(
        reg,
        names,
        config._REG_DIMENSIONS,
        adapters,
        _Th(temp, hum),
        _Co2(co2),
        _Time(minutes),
        external_read=external_read,
        clock=lambda: 0.0,
    )
    # Two ticks so slewed outputs have room to move toward target.
    engine.tick(now_s=0.0)
    engine.tick(now_s=1.0)
    return {n: adapters[i].value for i, n in enumerate(names)}


class TestScenarioTable:
    def test_cold_drives_heater_not_cooler(self):
        # cubensis day temp ideal 21; 20C is cold-ish → heater on, cooler off.
        cmd = _run_scenario(temp=20.0, hum=92.0, co2=700.0)
        assert cmd["heater"] > 0.0
        assert cmd["cooler"] == 0.0

    def test_hot_drives_cooling_not_heat(self):
        cmd = _run_scenario(temp=28.0, hum=92.0, co2=700.0)
        assert cmd["exhaust"] > 0.0
        assert cmd["heater"] == 0.0

    def test_dry_drives_humidifier(self):
        # RH modestly below the 95 ideal (dev ~33, minor band) → humidifier on
        # without tripping the emergency band that would force it off. Temp
        # sits at ideal so the humidifier's temp coupling contributes nothing
        # and dryness alone is what drives the command.
        cmd = _run_scenario(temp=21.0, hum=88.0, co2=700.0)
        assert cmd["humidifier"] > 0.0

    def test_high_co2_drives_exhaust(self):
        # At ideal temp and RH the surface contributes nothing, so the additive
        # CO2 term is the only thing that can open the fan.
        cmd = _run_scenario(temp=21.0, hum=95.0, co2=1400.0)
        assert cmd["exhaust"] > 0.0

    def test_hot_humid_conflict_cuts_humidifier(self):
        # temp dev 82 (sev 32, major band) + humidity dev 68, which is above
        # ideal and so clears the rule's humidity threshold of 0. The rule
        # fires WITHOUT tipping into emergency → humidifier forced 0, exhaust
        # & cooler preferred up.
        #
        # Temp must stay under deviation 90: at the 2026-08-01 anchors 28.2 C
        # IS severity 40, so the old fixture would have asserted the emergency
        # vector's humidifier cut and never exercised the conflict rule at all.
        cmd = _run_scenario(temp=26.8, hum=97.5, co2=700.0)
        assert cmd["humidifier"] == 0.0
        assert cmd["exhaust"] >= 60.0
        assert cmd["cooler"] >= 100.0

    def test_indoor_co2_leaves_headroom_above_it(self):
        # 1300 ppm is what a closed room reaches on a bad day; 2200 is a
        # chamber in real trouble. Under the old 1200 ppm ceiling both
        # saturated to the same maximum deviation and vented identically, so
        # the engine had no way to respond harder when it mattered.
        #
        # Read at the ideal temperature and humidity, so the temp/RH surface
        # contributes nothing and the CO2 term is the only thing separating the
        # two. That reading used to be impossible: the term was capped at 32,
        # under a floor of 40, so both cases tied at the floor. It is now the
        # sharpest way to state the requirement — CO2 alone must still open the
        # exhaust further as the air gets staler. The earlier 28 C anchor no
        # longer works: the retuned surface saturates the fan on temperature
        # alone there, and both cases tie at 100 for a different reason.
        indoor = _run_scenario(temp=21.0, hum=95.0, co2=1300.0)
        stale = _run_scenario(temp=21.0, hum=95.0, co2=2200.0)
        assert indoor["exhaust"] > 0.0
        assert stale["exhaust"] > indoor["exhaust"]

    def test_external_hotter_suppresses_exhaust(self):
        # temp 24.5 keeps the exhaust surface above its floor so the external
        # gate's suppression is visible, and below the deviation where the
        # surface saturates at 100 — where gated and ungated would tie.
        hot_inside = _run_scenario(temp=24.5, hum=92.0, co2=700.0)
        gated = _run_scenario(temp=24.5, hum=92.0, co2=700.0, external_read=lambda: (35.0, 50.0))
        assert gated["exhaust"] < hot_inside["exhaust"]


class _Switch:
    """Duck-typed on()/off() relay for driving a real adapter in a test."""

    def __init__(self):
        self.state = False

    def on(self):
        self.state = True

    def off(self):
        self.state = False


def _humidifier_relay():
    """Build the SHIPPED humidifier relay adapter (thresholds straight from config)."""
    import config
    from lib.regulation_adapters import RelayHysteresisAdapter

    a = config.DEVICE_CONFIG["regulation"]["regulators"]["humidifier"]["adapter"]
    switch = _Switch()
    adapter = RelayHysteresisAdapter(
        switch, a["on_above"], a["off_below"], a["min_on_s"], a["min_off_s"], name="humidifier"
    )
    return adapter, switch


def _settle(adapter, cmd, t0):
    """Apply a command twice, an hour apart, and return the settled time.

    The first apply on a fresh adapter only seeds its min-cycle timestamp, so
    any transition it wants is deferred; the second is past both dwell guards,
    leaving hysteresis as the only thing deciding.
    """
    adapter.apply(cmd, t0)
    adapter.apply(cmd, t0 + 3600.0)
    return t0 + 3600.0


def _relay_state_at(rh, temp=21.0, co2=700.0, start_on=False):
    """Settle the shipped humidifier relay at one (temp, RH) point.

    The default temperature is the cubensis day ideal, because the humidifier
    surface takes temp deviation as its y axis: hot → humidify more
    (evaporative cooling). Reading the RH band at any other temperature
    measures that coupling as well as the band, which is not what these tests
    are pinning.
    """
    adapter, switch = _humidifier_relay()
    t = 0.0
    if start_on:
        t = _settle(adapter, 100.0, t)
        assert switch.state is True, "precondition: relay should be on"
    cmd = _run_scenario(temp=temp, hum=rh, co2=co2)["humidifier"]
    _settle(adapter, cmd, t + 3600.0)
    return switch.state


class TestHumidifierRelayBand:
    """The humidifier is a RELAY: the command must actually cross its thresholds.

    Regression (2026-07-21): the operator reported T47 H16 C100 on the OLED —
    23.5 C, RH 80.4%, 1200 ppm — with the humidifier not running. The surface
    commanded 48.9 against an on_above of 60, so a chamber 12 RH points below
    its 92% ideal sat in a dead zone and never misted. Asserting the *command*
    alone could not catch that; these drive the shipped adapter.
    """

    def test_reported_dead_zone_now_energizes_relay(self):
        assert _relay_state_at(rh=80.4, temp=23.5, co2=1200.0) is True

    def test_relay_closes_below_the_calibrated_band(self):
        # Band is RH 92.7 (close) .. 94.6 (open) at the ideal temperature,
        # against the 75/95/102 anchors. It moved up with the 2026-07-31
        # retune (was 88 .. 91): the ideal went 92 → 95 and the surface ramp
        # was extended past ideal (bx_lo1 43 → 53) so the tent can actually
        # reach its setpoint instead of stalling 2.4 points below it.
        assert _relay_state_at(rh=87.0) is True

    def test_relay_opens_above_the_calibrated_band(self):
        assert _relay_state_at(rh=95.0, start_on=True) is False

    def test_relay_holds_inside_the_band(self):
        # Between the thresholds the relay keeps whatever state it had — that
        # is the hysteresis, and it must not collapse to a single switch point.
        assert _relay_state_at(rh=93.5, start_on=True) is True
        assert _relay_state_at(rh=93.5, start_on=False) is False

    def test_relay_stays_open_at_ideal(self):
        # At ideal the surface still trims (4.2), deliberately — but the trim
        # sits under off_below (7.0) so a relay actuator never closes on it.
        assert _relay_state_at(rh=95.0) is False

    def test_relay_still_misting_just_below_ideal(self):
        # The defect this retune fixes: with the old calibration the relay
        # opened at RH 89.6 against a 92 % ideal, so the tent stalled ~2.4
        # points short of its own setpoint and the operator bypassed the relay
        # onto mains. Anything inside the band, approached from below, must
        # still be misting — that is what makes the setpoint reachable.
        assert _relay_state_at(rh=94.0, start_on=True) is True
