# Golden-vector + scenario tests for the regulation matrix.
#
# The golden CSVs under tests/golden/ are generated by
# prototypes/plot_regulation_surfaces.py and blessed by the operator. The
# device surface math must reproduce them within +/-1 (this catches
# MicroPython float divergence near hinge breakpoints when run on-device, and
# catches accidental config/param drift when run on host — a changed surface
# fails until the golden CSV is regenerated).

from pathlib import Path

import pytest

_GOLDEN_DIR = Path(__file__).resolve().parent / "golden"


def _surface_names():
    import config

    regs = config.DEVICE_CONFIG["regulation"]["regulators"]
    return [n for n in config._REG_NAMES if regs[n].get("driven") == "surface"]


class TestGoldenVectors:
    def test_golden_file_exists_for_each_surface(self):
        for name in _surface_names():
            path = _GOLDEN_DIR / "regulation_{}.csv".format(name)
            assert path.exists(), "missing golden vectors for {} (run the host tool)".format(name)

    @pytest.mark.parametrize("name", _surface_names())
    def test_device_math_matches_golden(self, name):
        import config
        from lib.regulation_surface import evaluate, freeze_surface

        params = freeze_surface(config.DEVICE_CONFIG["regulation"]["regulators"][name]["surface"])
        path = _GOLDEN_DIR / "regulation_{}.csv".format(name)
        with open(path) as fh:
            header = fh.readline().strip()
            assert header == "x,y,out"
            for line in fh:
                x_s, y_s, out_s = line.strip().split(",")
                x, y, expected = float(x_s), float(y_s), float(out_s)
                got = evaluate(params, x, y)
                assert abs(got - expected) <= 1.0, "{} at ({},{}): {} vs golden {}".format(name, x, y, got, expected)


# ---------------------------------------------------------------------------
# Scenario table: (temp, RH, CO2) → expected actuation direction per regulator.
# ---------------------------------------------------------------------------


class _Adapter:
    def __init__(self, name):
        self.name = name
        self.value = 0.0
        self.active = False

    def apply(self, intensity, now_s):
        self.value = intensity
        self.active = intensity > 0.0


class _Th:
    def __init__(self, t, h):
        self.last_temperature = t
        self.last_humidity = h


class _Co2:
    def __init__(self, ppm):
        self.last_ppm = ppm


class _Time:
    def __init__(self, minutes):
        self._s = minutes * 60

    def get_seconds_since_midnight(self):
        return self._s


def _run_scenario(temp, hum, co2, minutes=720, external_read=None):
    import copy

    import config
    from lib.regulation_engine import RegulationEngine

    reg = copy.deepcopy(config.DEVICE_CONFIG["regulation"])
    if external_read is not None:
        reg["external_sensor"]["enabled"] = True
    names = config._REG_NAMES
    adapters = [_Adapter(n) for n in names]
    engine = RegulationEngine(
        reg,
        names,
        config._REG_DIMENSIONS,
        adapters,
        _Th(temp, hum),
        _Co2(co2),
        _Time(minutes),
        external_read=external_read,
        clock=lambda: 0.0,
    )
    # Two ticks so slewed outputs have room to move toward target.
    engine.tick(now_s=0.0)
    engine.tick(now_s=1.0)
    return {n: adapters[i].value for i, n in enumerate(names)}


class TestScenarioTable:
    def test_cold_drives_heater_not_cooler(self):
        # cubensis day temp ideal 24; 20C is cold-ish → heater on, cooler off.
        cmd = _run_scenario(temp=20.0, hum=92.0, co2=700.0)
        assert cmd["heater"] > 0.0
        assert cmd["cooler"] == 0.0

    def test_hot_drives_cooling_not_heat(self):
        cmd = _run_scenario(temp=28.0, hum=92.0, co2=700.0)
        assert cmd["exhaust"] > 0.0
        assert cmd["heater"] == 0.0

    def test_dry_drives_humidifier(self):
        # RH modestly below the 92 ideal (dev ~38, minor band) → humidifier on
        # without tripping the emergency band that would force it off.
        cmd = _run_scenario(temp=24.0, hum=88.0, co2=700.0)
        assert cmd["humidifier"] > 0.0

    def test_high_co2_drives_exhaust(self):
        cmd = _run_scenario(temp=24.0, hum=92.0, co2=1400.0)
        assert cmd["exhaust"] > 0.0

    def test_hot_humid_conflict_cuts_humidifier(self):
        # temp dev ~85 (sev 35) + humidity dev ~84 (sev 34): both in the major
        # band [30,40) so the mold-risk conflict rule fires WITHOUT tipping into
        # emergency → humidifier forced 0, exhaust & cooler preferred up.
        cmd = _run_scenario(temp=28.2, hum=97.5, co2=700.0)
        assert cmd["humidifier"] == 0.0
        assert cmd["exhaust"] >= 60.0
        assert cmd["cooler"] >= 100.0

    def test_external_hotter_suppresses_exhaust(self):
        hot_inside = _run_scenario(temp=27.0, hum=92.0, co2=700.0)
        gated = _run_scenario(temp=27.0, hum=92.0, co2=700.0, external_read=lambda: (35.0, 50.0))
        assert gated["exhaust"] < hot_inside["exhaust"]
